apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webapp
    spec:
      containers:
      - image: todotfacr.azurecr.io/ankit-antony-devops/bb-mernstack:98
        name: webapp
        imagePullPolicy: Always
        resources: {}
        ports:
          - containerPort: 5001 
status: {}

---

apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  ports:
  - port: 5001
    protocol: TCP
  selector:
    app: webapp
  type: LoadBalancer
